# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'twiths_' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'

pod 'GoogleMaps'
pod 'GooglePlaces'

  # Pods for twiths_

end
